#!/bin/bash

if [ $# -ne 1 ]; then
	echo "There should be exactly 1 argument\n"
	echo "Example usage: ./bake ha01"
	exit 1
fi

IFS='a' read -ra UB <<< "$1"

TITLE=$1
UBNR=$((10#${UB[1]})) # https://stackoverflow.com/a/11130324

echo "Compiling $TITLE"

WEG="./$TITLE/"

# Edit ubauf
sed -ri 's/\\def\\nrub\{[0-9]+\}/\\def\\nrub\{'$UBNR'\}/g' "main.tex"
# always use r before i

CURRPWD=$(pwd)

cd "$WEG"

# https://stackoverflow.com/a/21360477
# Compile
TEXINPUTS="$CURRPWD:" texliveonfly --compiler=pdflatex --arguments="-synctex=1 -interaction=nonstopmode --shell-escape -jobname=$TITLE" "../main.tex"

